apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: gin-basic-ci-only
spec:
  components:
    - name: template
      type: git-ci
      properties:
        repourl: "https://github.com/cnbailian/kubevela-examples-go.git"
        revision: "master"
        steps:
          - name: test-go
            image: golang:1.16
            command: [ "go" ]
            args: [ "version" ]
          - name: test-env
            image: golang:1.16
            command: [ "echo" ]
            args: [ "$(ENV)" ]
            env:
              - name: "ENV"
                value: "test-env"
      traits:
        - type: build-step
          properties:
            image: "docker.io/cnbailian/vela-basic-ci:v1.3"
            dockerfile: "gin-basic/Dockerfile"
        - type: taskrun
          properties:
            name: "run"
            saname: "build-sa"
