apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: gin-basic-ci-only
spec:
  components:
    - name: template
      type: git-template
      properties:
        repourl: "https://github.com/cnbailian/kubevela-examples-go.git"
        revision: "master"
        steps:
          - name: test-go
            image: golang:1.16
            command: [ "go" ]
            args: [ "version" ]
          - name: test-env
            image: golang:1.16
            command: [ "echo" ]
            args: [ "$(ENV)" ]
            env:
              - name: "ENV"
                value: "test-env"
          - name: build
            image: "gcr.io/kaniko-project/executor:latest"
            command: [
                "/kaniko/executor",
                "--dockerfile=gin-basic/Dockerfile",
                "--context=/workspace/repo",
                "--destination=docker.io/cnbailian/vela-basic-ci:v1.2",
                "--insecure",
            ]
            env:
              - name: "DOCKER_CONFIG"
                value: "/tekton/home/.docker"
    - name: ci-only-v1.2
      type: tekton-run
      properties:
        taskname: template
        saname: "build-sa"
