apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: gin-basic-ci
spec:
  components:
    - name: template
      type: git-template
      properties:
        repourl: "https://github.com/cnbailian/kubevela-examples-go.git"
        revision: "master"
        steps:
          - name: test-go
            image: golang:1.16
            command: [ "go" ]
            args: [ "version" ]
          - name: test-env
            image: golang:1.16
            command: [ "echo" ]
            args: [ "$(ENV)" ]
            env:
              - name: "ENV"
                value: "test-env"
      traits:
        - type: build-step
          properties:
            image: "docker.io/cnbailian/vela-basic-ci:v1.4"
            dockerfile: "gin-basic/Dockerfile"
    - name: cd-v1.4
      type: tekton-run
      properties:
        taskname: template
        saname: "build-sa"
      traits:
        - type: cd
          properties:
            application:
              components:
                - name: gin-basic-cd
                  type: basic
                  properties:
                    image: "cnbailian/vela-basic-ci:v1.4"
            appdeployment:
              appRevisions:
                - revisionName: cd-v1.4-v1
                  placement:
                    - distribution:
                        replicas: 1
