apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: tekton-run
  annotations:
    definition.oam.dev/description: "tekton TaskRun ComponentDefinition"
spec:
  workload:
    definition:
      apiVersion: tekton.dev/v1beta1
      kind: TaskRun
  status:
    healthPolicy: |
      isHealth: *false | bool
      for k, v in context.output.status.conditions {
        {
           if  (v.type == "Succeeded") && (v.status == "True"){
             isHealth: true
           }
        }
      }
  schematic:
    cue:
      template: |
        output: {
        	apiVersion: "tekton.dev/v1beta1"
        	kind:       "TaskRun"
        	metadata:
        		name: context.name
        	spec: {
        		if parameter.saname != _|_ {
        			serviceAccountName: parameter.saname
        		}
        		taskRef: {
        			name: parameter.taskname
        		}
        		resources: {
        			inputs: [{
        				name: "repo"
        				resourceRef: {
        					name: parameter.taskname
        				}
        			}]
        		}
        	}
        }

        parameter: {
        	// +usage=Specify the taskrun TaskRef
        	taskname: string

        	// +usage=Specify the taskrun ServiceAccountName
        	saname: string
        }
